### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by yaolp123** [srkesler/bnets#2]
Dear authors: 
    Recently I  have looking your this project and feel interested in it ! could have a introduction, like paper or tutorial of this project, and could have a dataset of this project.  Thanks a lot! I am looking forward to your reply Sincerely!

Best regards.

**Comment by srkesler** [comment]
Hello, thanks for your interest.  We do not have a paper or tutorial at this time.  However, all you need to do is follow the instructions in the GATcmd_Wrapper.m script where it says “USER EDIT HERE”. 

We do not have datasets but you can obtain these from other sources such as Human Connectome Project, EBRAINS, or Brain Connectivity Toolbox.
